- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/🆕-feature-request.md
- .github/ISSUE_TEMPLATE/🐞-bug-ui-ux.md
- .github/ISSUE_TEMPLATE/📚-add-a-documentation-report.md
- .github/ISSUE_TEMPLATE/🪲-bug-python-deployment.md
- .github/PULL_REQUEST_TEMPLATE/bug.md
- .github/PULL_REQUEST_TEMPLATE/docs.md
- .github/PULL_REQUEST_TEMPLATE/features.md
- .github/pull_request_template.md
Copying GitHub templates from `argilla` repository.
> chore: add GitHub templates

- CHANGELOG.md
- CITATION.cff
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Adding some missing files like `CODE_OF_CONDUCT.md`, `CHANGELOG.md` and others.
> chore: add code of conduct and others

- CHANGELOG.md
- src/argilla_server/search_engine/commons.py
- tests/unit/search_engine/test_commons.py
This PR fixes problems filtering by similarity search in combination with text queries. Now, the text query is added to the query filters.
Closes https://github.com/argilla-io/argilla/issues/4387
Running locally.
**Checklist**
> fix: combine text with similarity search

- .env.dev
- .env.test
- README.md
- pyproject.toml
This PR includes some quality of life improvements to work in development adding the following:
* a dotenv file at `env.dev` defining environment variables to work in development. This file will be used for all `pdm` commands by default.
* a dotenv file at `env.test` defining environment variables to be used by our test suite. It will overwrite some environment variables defined by `env.dev`, specifically defining a different value for `ARGILLA_DATABASE_URL` so we have two different databases, one for development an another one for testing.
* `pdm cli` custom command to run Argilla cli easily.
* `pdm server` custom command to run Unicorn development server (reloading files).
* `pdm migrate` custom command to run database migrations with alembic.
* `pdm test` custom command to run the …
> feat: add dotenv files for PDM custom commands

- CHANGELOG.md
- src/argilla_server/apis/v1/handlers/questions.py
- src/argilla_server/contexts/datasets.py
- src/argilla_server/contexts/questions.py
- src/argilla_server/schemas/v1/questions.py
- tests/unit/api/v1/test_questions.py
This PR adds support for updating question options for label and multi-label question settings. 
Refs https://github.com/argilla-io/argilla/issues/4366
Running locally
**Checklist**
> feat: Allow update question labels

- README.md
I updated the readme to align with https://github.com/argilla-io/argilla
Closes #40 
N.A.
N.A.
**Checklist**
N.A.
> docs: 40 docs positioning workshop

- src/argilla_server/contexts/datasets.py
This PR review the record creation/modification and splits the creation/modification for each of its relationships (responses, suggestions and vectors)
Also, the response validation function expects a record as an argument instead of a dataset (the dataset must be available from the record)
Closes #<issue_number>
**Checklist**
> refactor: Split build record and its relatioships

- src/argilla_server/contexts/datasets.py
- src/argilla_server/contexts/records.py
- src/argilla_server/models/database.py
- src/argilla_server/schemas/v1/records.py
- src/argilla_server/validators/records.py
- tests/unit/api/v1/test_datasets.py
This PR introduces new classes for record create/update validation in the new record bulk endpoint. Also, replace old validation flows with new ones used in datasets context.
TODO: Add some tests for validations records bulk endpoint
**Checklist**
> feat: add record validators

- src/argilla_server/apis/v1/handlers/datasets/records.py
- src/argilla_server/contexts/datasets.py
- src/argilla_server/contexts/questions.py
- src/argilla_server/contexts/records.py
- src/argilla_server/models/database.py
- src/argilla_server/schemas/v1/records.py
- src/argilla_server/validators/records.py
- tests/unit/api/v1/datasets/records/test_create_dataset_records.py
- tests/unit/api/v1/datasets/records/test_update_dataset_records.py
- tests/unit/api/v1/test_datasets.py
This PR creates a new endpoint for creating or updating records in bulk. 
- The endpoint is defined as `POST /api/v1/datasets/:dataset_id/records/bulk`
- The request body is an `items` attribute including the records to create or update
- This endpoint uses the schemas created for the current created or updated endpoints `RecorCreate` and `RecordUpdate` but this may change in the future.
- There is no validation integration yet.
**Checklist**
> feat: create or update records bulk

- src/argilla_server/apis/v1/handlers/datasets/records.py
- src/argilla_server/contexts/records.py
- tests/unit/api/v1/datasets/records/test_create_dataset_records_bulk.py
This PR adds code to update records in bulk using the `external_id` (and dataset_id) attribute.
Refs: https://github.com/argilla-io/argilla-server/issues/79
**Checklist**
> feat: update records by `external_id`

- CHANGELOG.md
- src/argilla_server/contexts/questions.py
- src/argilla_server/schemas/v1/questions.py
- src/argilla_server/validators/questions.py
- tests/unit/api/v1/datasets/test_create_dataset_question.py
- tests/unit/api/v1/questions/test_update_question.py
This PR adds support for configure overlapping for span questions on creation and update.
Refs https://github.com/argilla-io/argilla/issues/4694
**Checklist**
> feat: expose `allow_overlapping` property

- CHANGELOG.md
- src/argilla_server/apis/v1/handlers/datasets/datasets.py
- src/argilla_server/contexts/datasets.py
- src/argilla_server/schemas/v1/datasets.py
- tests/unit/api/v1/datasets/test_get_dataset_progress.py
This PR add a new endpoint with the following signature:
`GET /api/v1/datasets/:dataset_id/progress`
This endpoint will return a response with the following format:
```json
{
"total": 8,
"submitted": 2,
"discarded": 2,
"conflicting": 1,
"pending": 3,
}
```
The attributes will return an integer with the following logic:
* `total`: the total number of records for the specified dataset.
* `submitted`: the number of records for the specified dataset with at least one response with `submitted` status and no responses with `discarded` status.
* `discarded`: the number of records for the specified dataset with at least one response with `discarded` status and no responses with `submitted` status.
* `conflicting`: the number of records for the specified dataset with at least one response with …
> feat: add new endpoint to get the progress of a dataset

- CHANGELOG.md
- src/argilla_server/contexts/questions.py
- src/argilla_server/schemas/v1/questions.py
- src/argilla_server/validators/questions.py
- src/argilla_server/validators/response_values.py
- tests/unit/api/v1/datasets/test_create_dataset_question.py
- tests/unit/api/v1/questions/test_update_question.py
- tests/unit/api/v1/records/test_create_record_response.py
- tests/unit/api/v1/records/test_upsert_suggestion.py
Feature branch to support span questions overlapping.
Refs https://github.com/argilla-io/argilla/issues/1750
**Checklist**
> feat: overlapped span questions

- docker/quickstart/Dockerfile
- docker/quickstart/Procfile
- docker/quickstart/requirements.txt
- docker/quickstart/scripts/start_argilla_server.sh
- docker/quickstart/scripts/start_quickstart_argilla.sh
This is an experimental PR to see if it's possible to see ElasticSearch logs on HF space logs. In order to do this I'm using honcho Python package with a `Procfile` where ElasticSearch and argilla server are executed.
Refs https://github.com/argilla-io/argilla/issues/4689
**Checklist**
> feat: use honcho to manage processes with quickstart Dockerfile

- CHANGELOG.md
- src/argilla_server/alembic/versions/ca7293c38970_change_suggestions_score_column_to_json.py
- src/argilla_server/models/database.py
- src/argilla_server/schemas/v1/suggestions.py
- src/argilla_server/validators/suggestions.py
- tests/unit/api/v1/records/test_upsert_suggestion.py
This PR add the necessary changes so now suggestions allow a single score value or a list of score values for `score` attribute.
This change has the following restrictions:
* `score` is optional (as before).
* `score` can be a score value in the range `[0, 1]` (as before).
* `score` can be a non empty list of score values in the range `[0, 1]` (added change).
*  when `score` is a list of scores values is not possible to specify `None` as a score value, so we are losing the optionality of scores when defined as a list (added change).
* when `score` is a list of scores values the number of items inside the list should match with the number of items in the `value` attribute (added change).
> [!NOTE]
> I will create another PR removing `score` attribute for suggestions linked to span …
> feat: suggestion score supporting multiple scores

- .github/workflows/package.yml
- .github/workflows/run-python-tests.yml
- src/argilla_server/contexts/accounts.py
- src/argilla_server/contexts/datasets.py
This PR add changes so we can execute unit tests on GitHub workflows using PostgreSQL.
**Checklist**
> feat: GitHub actions running tests with PostgreSQL

- pdm.lock
- pyproject.toml
Removes `psycopg2-binary` dependency.
**Checklist**
> chore: Remove psycopg2-binary from .toml

- src/argilla_server/alembic/versions/ca7293c38970_change_suggestions_score_column_to_json.py
This PR includes changes implementing the missing rollback/downgrade for migration updating `score` column for suggestion to be of type JSON.
The discussed logic was the following:
1. Preserve values that have a single float value. 
2. Discard anything else setting it as `NULL` (so list of floats are downgraded and set to `NULL`).
I have tested the migration successfully with SQLite and PostgreSQL.
Closes #113 
**Checklist**
> feat: suggestions multi score downgrade implementation

- src/argilla_server/models/database.py
- src/argilla_server/validators/vectors.py
- tests/unit/api/v1/datasets/records/records_bulk/test_dataset_records_bulk_with_suggestions.py
- tests/unit/api/v1/datasets/records/records_bulk/test_dataset_records_bulk_with_vectors.py
This PR adds missing tests for bulk records with vectors
**Checklist**
> tests: Add tests for vectors

- src/argilla_server/alembic/versions/ca7293c38970_change_suggestions_score_column_to_json.py
This PR improves the database migration changing `score` column from `suggestions` table to be JSON adding an additional update so `score` values associated to suggestions with `value` using an array are set to `NULL`.
This update is necessary because we don't want to support suggestions with `value` having an array and only one float in the `score` column (when they should have multiple `score` values).
Closes #128
**Checklist**
> feat: set suggestions score to null when migrating score to JSON and value attribute is an array

- .env.dev
- src/argilla_server/search_engine/base.py
- src/argilla_server/search_engine/commons.py
- tests/unit/search_engine/test_commons.py
This PR adapts the search engine to support filters based on query strings applied to fields. This PR only works at the search engine level and the search endpoints are unaffected.
**Checklist**
> feat: support query string filters for engine

- src/argilla_server/telemetry.py
This PR adds the telemetry context attributes as part of the user traits since the context values are not available for analytics.
**Checklist**
> fix(telemetry): Identify user with system info 

- src/argilla_server/telemetry.py
- src/argilla_server/utils/_telemetry.py
This PR divide deployment into 3 different types: `server`, `quickstart` and `huggingface_space`.
**Checklist**
> feat(telemetry): Define three types of deployments
