argilla-io/argilla-server

- .github/workflows/build-python-package.yml
- .github/workflows/package.yml
- .github/workflows/run-python-tests.yml
- src/argilla_server/_version.py
Looks like a bug on [setup-pdm](https://github.com/pdm-project/setup-pdm) action was not correctly reading the Python version from `pyproject.toml` and causing to use the default version from `ubuntu-latest` container (v3.12 for this case).
Upgrading from `pdm-project/setup-pdm@v3` to `pdm-project/setup-pdm@v4` looks like fixing the issue.
**Checklist**
> fix: publish of argilla-server Python package to PyPI using wrong Python version

- src/argilla_server/__init__.py
- src/argilla_server/pydantic_v1/__init__.py
This PR allows the import of `argilla_server` modules when the Pydantic v2 package is installed. You can find the related work in [the `argilla` repository](https://github.com/argilla-io/argilla/pull/4537)
**Checklist**
> Allow import `argilla_server` module with pydantic 2.0

- src/argilla_server/apis/v1/handlers/oauth2.py
- src/argilla_server/security/authentication/oauth2/settings.py
- tests/unit/api/v1/test_oauth2.py
When `.oauth.yaml` file contains `enabled: false`, the oauth endpoints return the configured provider info. This PR fixes it and set an empty list when `enabled=False`
Running locally and HF spaces
**Checklist**
> fix: Clean providers list when oauth config is disabled

- CHANGELOG.md
- src/argilla_server/_app.py
- src/argilla_server/static_rewrite.py
- tests/unit/test_app.py
This PR introduces changes to allow configuring a base path using `ARGILLA_BASE_URL` without requiring an external proxy. 
If you want to run argilla behind a proxy without changing base URL (which means defining a pathRewrite rule in your proxy), you should use the `UVICORN_ROOT_PATH` env variable. For more info visit https://fastapi.tiangolo.com/advanced/behind-a-proxy/#behind-a-proxy and https://www.uvicorn.org/settings/
Related PR: https://github.com/argilla-io/argilla/pull/3543
Closes https://github.com/argilla-io/argilla/issues/4568 …
> fix: Using `settings.base_url` to setup base url path

- pyproject.toml
Also, the provided scripts to build the docker images tag the generated images with the `local` tag to avoid image version conflicts with those generated outside
> fix: Add missing `httpx` dependency

- docker/quickstart/scripts/start_quickstart_argilla.sh
- docker/server/scripts/start_argilla_server.sh
- pyproject.toml
This fix is related to work developed in #14
This change is still compatible with a proxied configuration. To make it work using an nginx proxy configuration as defined [here](https://github.com/argilla-io/argilla/blob/develop/docker/nginx/nginx.conf), you should adapt the target server to adding the configured base URL:
```conf
events {}
http {
server {
listen 80;
location /argilla/ {
proxy_pass http://argilla:6900/argilla; # <- this line adds the `/argilla` path
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
}
}
}
```
> fix: remove `--root-path` param when running the docker image with the `ARGILLA_BASE_URL` enabled

- src/argilla_server/static_rewrite.py
Otherwise, the SPA flow when loading the application from a shared URL
This error was introduced in this [PR](https://github.com/argilla-io/argilla-server/pull/14)
> fix: redirect to index.html

- pdm.lock
- pyproject.toml
- tests/conftest.py
This PR add changes so the test suite is fully supported by PostgreSQL (and with SQLite too):
* Change `pytest-asyncio` version to use 0.21.1, latest version 0.23.3 has https://github.com/pytest-dev/pytest-asyncio/issues/706 modifying how event loops are managed.
* Uncomment `event_loop` fixture so tests works using PostgreSQL.
* I have updated the `pdm.lock` file so now `pdm install -G postgresql` should work properly.
**Checklist**
> fix: test suite is now fully passing using SQLite or PostgreSQL

- src/argilla_server/apis/v1/handlers/datasets/records.py
- src/argilla_server/search_engine/commons.py
- src/argilla_server/search_engine/elasticsearch.py
- tests/unit/api/v1/test_datasets.py
- tests/unit/api/v1/test_list_dataset_records.py
- tests/unit/search_engine/test_commons.py
This PR updates the `search` method of the `SearchEngine` to sort the records for each user in a different way using the [`random_score`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-random) function and the user id as seed for this function to make the sort deterministic between user sessions. In addition, the default sort of the records using the `inserted_at` field in ascending order has been removed.
The affected endpoints by this change are `GET /api/v1/me/datasets/:dataset_id/records` and `GET /api/v1/me/datasets/:dataset_id/records/search`.
If we finally decide to have this feature as default in the server, then before merging:
Change is already being used in …
> feat: add different deterministic sorting of records per user

- CHANGELOG.md
- src/argilla_server/security/settings.py
- tests/unit/security/test_settings.py
This PR removes support for old `ARGILLA_LOCAL_AUTH_*` environment variables. 
Closes https://github.com/argilla-io/argilla/issues/4542
**Checklist**
> remove backward compatibility with argilla local auth  env variables

- pdm.lock
- pyproject.toml
This PR add `pytest-randomly` as dependency so our test suite is executed in a random way.
After this change a new `Using --randomly-seed=2880304302` line will appear when tests are executed, showing the random seed that it's used in the case that you need to reproduce the order and debug some error.
Refs #44 
**Checklist**
> feat: add pytest-randomly as tests dependency

- src/argilla_server/apis/v1/handlers/suggestions.py
- src/argilla_server/contexts/questions.py
- src/argilla_server/schemas/v1/questions.py
- tests/factories.py
- tests/unit/api/v1/test_questions.py
This PR add changes so span questions can be updated and labels on settings reorder. The labels can not be changed only reordered as we are already doing for label and multi label questions.
Closes #49 
**Checklist**
> feat: update span questions

- src/argilla_server/contexts/datasets.py
- src/argilla_server/models/database.py
- src/argilla_server/models/questions.py
- tests/unit/api/v1/records/test_create_record_response.py
- tests/unit/api/v1/records/test_upsert_suggestion.py
This PR add additional validations for span responses and suggestions:
* Check that the required `field` to be annotated by the response or suggestion is present in the associated record.
* Check that annotation `start` attribute is lower than the length in characters of the associated record field.
* Check that annotation `end` attribute is lower or equal than the length in characters of the associated record field.
These validations are done in the `check_response` function present in `questions` models package.
Refs #45
**Checklist**
> feat: add additional validations for span responses and suggestions

- CHANGELOG.md
- src/argilla_server/contexts/datasets.py
- src/argilla_server/models/database.py
- src/argilla_server/models/questions.py
- src/argilla_server/schemas/v1/suggestions.py
- tests/unit/api/v1/records/test_create_record_response.py
- tests/unit/api/v1/records/test_upsert_suggestion.py
- tests/unit/api/v1/test_datasets.py
- tests/unit/api/v1/test_records.py
- tests/unit/api/v1/test_suggestions.py
Add `inserted_at` and `updated_at` fields to `Suggestion` schema for API v1.
Refs #45 
**Checklist**
> feat: add timestamps fields to suggestion schema

- CHANGELOG.md
- src/argilla_server/apis/v1/handlers/datasets/questions.py
- src/argilla_server/apis/v1/handlers/questions.py
- src/argilla_server/apis/v1/handlers/records.py
- src/argilla_server/apis/v1/handlers/suggestions.py
- src/argilla_server/contexts/datasets.py
- src/argilla_server/contexts/questions.py
- src/argilla_server/contexts/search.py
- src/argilla_server/models/questions.py
- src/argilla_server/schemas/v1/questions.py
- src/argilla_server/schemas/v1/suggestions.py
- tests/factories.py
- tests/unit/api/v1/datasets/test_create_dataset_question.py
- tests/unit/api/v1/datasets/test_questions.py
- tests/unit/api/v1/records/test_create_record_response.py
- tests/unit/api/v1/records/test_upsert_suggestion.py
- tests/unit/api/v1/test_datasets.py
- tests/unit/api/v1/test_questions.py
- tests/unit/api/v1/test_records.py
- tests/unit/api/v1/test_suggestions.py
This PR add changes so we can create responses for span questions.
Closes #45
**Checklist**
> feat: create span question responses

- src/argilla_server/models/questions.py
- src/argilla_server/schemas/v1/commons/__init__.py
- src/argilla_server/schemas/v1/commons/suggestions.py
- src/argilla_server/schemas/v1/suggestions.py
- tests/unit/api/v1/records/test_upsert_suggestion.py
This PR add a small addition to value items specified for responses and suggestions adding `score` field.
As we now the `check_response` implementation only validates so still any field specified in the value for responses and suggestions will be inserted in the database. Because of this we have some caveats:
* `score` using an integer like `1` will be store as `1` without being transformed to float.
* When `score` is not specified we will not store inside the JSON column `{..., "score": None}` instead `score` attribute will not be available.
* It's possible to specify `score` for responses not only suggestions.
Closes #55 
(Please …
> feat: add score to span suggestions

- src/argilla_server/apis/v1/handlers/datasets/questions.py
- src/argilla_server/contexts/questions.py
- tests/unit/api/v1/datasets/test_create_dataset_question.py
This PR adds a server validation to avoid creating several span questions using the same field. 
**Checklist**
> feat: add uniqueness field validation for span questions

- src/argilla_server/apis/v1/handlers/datasets/__init__.py
- src/argilla_server/apis/v1/handlers/datasets/records.py
- src/argilla_server/apis/v1/handlers/datasets/records_search.py
This PR is the first of a PR series to tackle issue #79.
This PR move the search records-related endpoints to a separate module `records_search`. This lets the `records` module with a more controllable size. Otherwise, the module becomes unmanageable.
The PR does not modify any existing behaviour. 
Refs #79 
**Checklist**
> refactor: Move records search-related endpoints to a separate module

- tests/unit/cli/search_engine/conftest.py
This is a fix to a problem running reindex cli tests using PostgreSQL (it's not reproducible using SQLite).
**Checklist**
> fix: mock AsyncSessionLocal to flix problems with flaky cli reindex test

- CHANGELOG.md
- src/argilla_server/apis/v0/handlers/users.py
- src/argilla_server/apis/v0/handlers/workspaces.py
- tests/unit/api/v0/test_workspaces.py
This PR removes the `GET /api/workspaces` endpoint which is not used anymore for a while.
**Checklist**
> refactor: delete old list workspaces endpoint

- CHANGELOG.md
- docker/quickstart/Dockerfile
This PR fix a typo on the definition of the `ES_JAVA_OPTS` environment value and increase the heap start and maximum values from `512m` to `1g`.
The motivation for this change is coming from some users that have ElasticSearch not working properly (stop executing) on HF spaces.
**Checklist**
> chore: increase heap limit for ElasticSearch from 512m to 1g for Quickstart docker image

- CHANGELOG.md
- src/argilla_server/apis/v0/handlers/info.py
- src/argilla_server/services/info.py
- tests/unit/api/v0/info/__init__.py
- tests/unit/api/v0/info/test_api_status.py
This PR add changes to `/api/_status` endpoint exposing Hugging Face spaces environment variables only when a `SPACE_ID` environment variable is available.
The response of the endpoint will gain a new `huggingface` attribute with the following structure:
```json
{
"space_id": "space-id",
"space_title": "space-title",
"space_subdomain": "space-subdomain",
"space_host": "space-host",
"space_repo_name": "space-repo-name",
"space_author_name": "space-author-name",
"space_persistant_storage_enabled": true
}
```
If `SPACE_ID` environment variable is not available so we are not running Argilla inside a Hugging Face space then the `huggingface` attribute inside the response will not be available.
> [!NOTE]
> I will add an additional PR including a new setting so it's possible to disable the …
> feat: expose Hugging Face spaces environment variables on `/api/_status` endpoint

- src/argilla_server/schemas/v1/suggestions.py
- src/argilla_server/validators/suggestions.py
- tests/unit/api/v1/datasets/records/test_create_dataset_records.py
- tests/unit/api/v1/datasets/records/test_update_dataset_records.py
- tests/unit/api/v1/records/test_upsert_suggestion.py
This PR move all suggestion `score` validations to `SuggestionCreateValidator` and add a new one checking that `value` and `score` attributes have the same cardinality.
The additional validation will raise an error when a suggestion have a single item inside `value` attribute and a list of items inside `score`.
Refs https://github.com/argilla-io/argilla/issues/4638
**Checklist**
> feat: move suggestion score validations to `SuggestionCreateValidator` and add a missing cardinality validation for value and score attributes

- CHANGELOG.md
- src/argilla_server/contexts/questions.py
- src/argilla_server/enums.py
- src/argilla_server/schemas/v1/questions.py
- tests/factories.py
- tests/unit/api/v1/datasets/questions/__init__.py
- tests/unit/api/v1/datasets/questions/test_create_dataset_question.py
- tests/unit/api/v1/datasets/questions/test_list_dataset_questions.py
- tests/unit/api/v1/questions/__init__.py
- tests/unit/api/v1/questions/test_update_question.py
- tests/unit/api/v1/test_datasets.py
- tests/unit/api/v1/test_questions.py
This PR add changes so a new attribute with name `options_order` can be set for multi selection question settings.
This attribute is an enumerable that can have the following values:
* `natural`: the default value, showing that the options/labels should be ordered in their natural order where they have been specified for the questions.
* `suggestion`: showing that options/labels should be ordered giving priority to the labels that have suggestions (having or not an assigned `score`) and sorting by `score` when available.
Some more details about this implementation:
- When retrieving a multi label selection question without `options_order` in his settings, `options_order: natural` will be returned inside the settings.
- When creating a multi label selection question if `options_order` has …
> feat: add support to new `options_order` settings attribute for multi label selection questions

- CHANGELOG.md
- src/argilla_server/apis/routes.py
- src/argilla_server/apis/v1/handlers/authentication.py
- src/argilla_server/contexts/accounts.py
- tests/unit/api/v1/authentication/__init__.py
- tests/unit/api/v1/authentication/test_create_token.py
This PR implements a new endpoint on API v1 to create tokens for users. It works the same than the one in API v0 with small changes.
The new endpoint created is `POST /api/v1/token`. I have used `/token` instead of `/login` because I think we are creating tokens and it's better if we continue using that naming for it. 
@frascuchon tell me if we still have a good reason for rename it to `/login` and I will change it if necessary.
Closes #137 
**Checklist**
> feat: add new endpoint to create user tokens on API v1

- CHANGELOG.md
- src/argilla_server/apis/v1/handlers/users.py
- src/argilla_server/schemas/v1/users.py
- tests/unit/api/v1/users/__init__.py
- tests/unit/api/v1/users/test_get_current_user.py
This PR creates a new `/api/v1/me` endpoint with similar functionality to the old `/me` endpoint from API v0.
The following changes are included:
* `full_name` user attribute is not used in the new `User` v1 schema. Instead the frontend should concatenate `first_name` and `last_name` if necessary.
* `workspaces` user attribute is not used in the new `User` v1 schema. `/api/v1/me/workspaces` could be used instead.
Closes #139
**Checklist**
> feat: migrate `/api/me` endpoint to `/api/v1/me`

- CHANGELOG.md
- src/argilla_server/contexts/settings.py
- src/argilla_server/schemas/v1/settings.py
- src/argilla_server/settings.py
- tests/unit/api/v1/settings/test_get_settings.py
We know that the exposed environment variable from HF has a typo using `PERSISTANT_STORAGE_ENABLED` instead of `PERSISTENT_STORAGE_ENABLED`.
Instead of aligning with that typo with this PR we will use the correct spelling even if internally we are using the HF environment variable with the typo.
Refs #123 
**Checklist**
> fix: HF typo using persistent instead of persistant

- CHANGELOG.md
- src/argilla_server/apis/routes.py
- src/argilla_server/apis/v1/handlers/info.py
- src/argilla_server/schemas/v1/info.py
- tests/unit/api/v1/info/__init__.py
- tests/unit/api/v1/info/test_get_version.py
With this PR I'm creating a new endpoint on API v1 `GET /api/v1/version` to return the current argilla version.
I renamed it to `/api/v1/version` instead of `/api/v1/info` because at the end we are only returning the version.
Closes #161
**Checklist**
> feat: migrate `/api/_info` endpoint to `/api/v1/version`
